### ISSUE TITLE
GraphQL error/confusion

### ISSUE THREAD

**Issue by adilasif** [chingu-x/feedback#52]
Upon submitting my Voyage application, I received a GraphQL error stating something about an overflow (255). I don't remember exactly what it said, as I just clicked to "Go back" and re-submit, thinking I needed to shorten a response or something. Subsequent submissions throw a duplicate form submission GraphQL error. I am unsure if my submission was recorded, as when I look at the Voyage Portal, I only see the "Apply" button.

**Comment by the-vampiire** [comment]
i cant find anything related to to this error in the logs. i see that your new voyage user application was saved but your profile was not updated to reflect the data. 

when you go to `https://beta.chingu.io/voyage/application/1` does the title at the top say Voyage Application or New Voyage User?

**Comment by adilasif** [comment]
It says "New Voyage User"

**Comment by the-vampiire** [comment]
working on a fix right now. get back to you soon

**Comment by the-vampiire** [comment]
![screen shot 2018-11-08 at 4 30 29 pm](https://user-images.githubusercontent.com/25523682/48228597-a09a2180-e373-11e8-96d8-b42e9a6cf8f7.png)
all sorted out. thanks for catching that bug. you were right - it was due to the character length for those sections. i upped them to 1000. 

your status has been updated to voyage ready. if you go back to the application [here](https://beta.chingu.io/voyage/application/1) you should see Voyage Application at the top and can fill it out now. 

cool picture man!
